### ISSUE TITLE
Automatically delete after saving when opening the user manual PDF 使用指南PDF打开以后保存后自动给删除 #1573 

### ISSUE THREAD

**Issue by Dev-Wiki** [plantuml/plantuml.com#17]
"The official website containing ads can be understood. Having ads when viewing the user manual online can also be understood.

However, what does it mean by 'automatically delete after saving' when opening the online manual PDF?

If downloading the user manual is not supported, please make it clear and disable the download button."

官方网站带有广告能理解, 使用指南在线查看有广告也能理解, 

但是打开在线指南pdf 保存后自动给删除是几个意思? 

如果不支持下载使用指南, 直接说明并且关闭下载按钮吧.

[Video](https://github.com/plantuml/plantuml/assets/12946956/bd97d83e-24b4-4af7-a8f5-754c1068f3aa)

**Comment by Dev-Wiki** [comment]
https://github.com/plantuml/plantuml.com/issues/17

**Comment by arnaudroques** [comment]
Sorry about the ads :-)

There must be an issue somewhere: we do not prevent users from downloading the PDF file and keeping it locally.
I am not sure about what is going on.

As workaround, you can find here the origin of those files here:

https://pdf.plantuml.net/PlantUML_Language_Reference_Guide_en.pdf
https://pdf.plantuml.net/PlantUML_Language_Reference_Guide_zh.pdf

Tell us if it is not working for you!

**Comment by Dev-Wiki** [comment]
> Sorry about the ads :-)
> 
> There must be an issue somewhere: we do not prevent users from downloading the PDF file and keeping it locally. I am not sure about what is going on.
> 
> As workaround, you can find here the origin of those files here:
> 
> https://pdf.plantuml.net/PlantUML_Language_Reference_Guide_en.pdf https://pdf.plantuml.net/PlantUML_Language_Reference_Guide_zh.pdf
> 
> Tell us if it is not working for you!

谢谢，使用你给的链接可以正常下载保存。
Thank you, I can download and save normally using the link you gave me.
